# Generated by Django 4.2.5 on 2023-09-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_delete_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="enable_comment",
            field=models.BooleanField(default=True),
        ),
    ]
