# Generated by Django 4.2.4 on 2024-03-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_like"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
